#ifndef SCENES_INDEX_H
#define SCENES_INDEX_H

namespace Scenes{
    enum SceneIndex {
        TITLE,
        PROLOG_1,
        PROLOG_2A, PROLOG_2B, PROLOG_2C,
        PROLOG_3,
        PROLOG_4A, PROLOG_4B, PROLOG_4C,
        PROLOG_5,
        PROLOG_6A, PROLOG_6B,
        PROLOG_7A, PROLOG_7B,
        PROLOG_8,
        PROLOG_9,
        PROLOG_10A, PROLOG_10B,
        PROLOG_11A, PROLOG_11B,
        PROLOG_12A, PROLOG_12B,
        PROLOG_13,
        PROLOG_14,
        PERASAAN_1,
        PERASAAN_2A, PERASAAN_2B, PERASAAN_2C,
        PERASAAN_3,
        PERASAAN_4A, PERASAAN_4B,
        PERASAAN_5A, PERASAAN_5B, PERASAAN_5C,
        PERASAAN_6,
        PERASAAN_7,
        PERASAAN_8A, PERASAAN_8B,
        PERASAAN_9A, PERASAAN_9B,
        PERASAAN_10,
        PERASAAN_11,
        KERAGUAN_1,
        KERAGUAN_2A, KERAGUAN_2B,
        KERAGUAN_3A, KERAGUAN_3B,
        KERAGUAN_4,
        KECEMBURUAN_1,
        KECEMBURUAN_2A, KECEMBURUAN_2B,
        KECEMBURUAN_3,
        KECEMBURUAN_4A, KECEMBURUAN_4B,
        KECEMBURUAN_5,
        KECEMBURUAN_6,
        KECEMBURUAN_7A, KECEMBURUAN_7B,
        PERJALANAN_1,
        PERJALANAN_2A, PERJALANAN_2B,
        ENDING_1, 
        ENDING_2A, ENDING_2B,
        ENDING_3A, ENDING_3B, 
        ENDING_4, 
        ENDING_5,
        END_TITLE
    };
}

#endif